# Generated by Django 2.2.5 on 2019-09-29 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeReference',
            fields=[
                ('status_code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('status_description', models.CharField(max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_code', models.CharField(max_length=30, unique=True)),
                ('customer_first_name', models.CharField(max_length=30)),
                ('customer_last_name', models.CharField(max_length=30)),
                ('delivery_address', models.TextField(max_length=100)),
                ('status_code', models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='app.CodeReference')),
            ],
        ),
    ]
